# Generated by Django 3.2.12 on 2022-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220520_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=1000),
        ),
    ]
