# Generated by Django 3.2.12 on 2022-05-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watch_movie',
        ),
    ]
